### ISSUE TITLE
Possible solution to Solid principles violation

### ISSUE THREAD

**Issue by NoeSaltos** [GordonL0049/OpenAI#2]
**SRP:**
![image](https://github.com/GordonL0049/OpenAI/assets/119470611/c9891e36-8508-4155-a219-4098fd4ac3f7)
![image](https://github.com/GordonL0049/OpenAI/assets/119470611/42de77a5-2251-4217-b2cf-616f6cbaf50f)
![image](https://github.com/GordonL0049/OpenAI/assets/119470611/2d3cf7b4-c3f6-47e5-b8a4-ef7bca3f64d1)
UML:
![image](https://github.com/GordonL0049/OpenAI/assets/119470611/18c3527d-d2e0-4af5-8d97-1717c342db00)
**OCP:**
![image](https://github.com/GordonL0049/OpenAI/assets/119470611/fa8c3fd0-0766-496d-ba1f-20867e52df38)
UML:
![image](https://github.com/GordonL0049/OpenAI/assets/119470611/a5835936-5988-499d-81b7-54160b34219e)
**LSP:**
![image](https://github.com/GordonL0049/OpenAI/assets/119470611/19d89d2c-2e81-4277-9fc3-c96dd5e1378b)
![image](https://github.com/GordonL0049/OpenAI/assets/119470611/21b6d337-b2ed-4675-a6b9-8ac696c755de)
UML:
![image](https://github.com/GordonL0049/OpenAI/assets/119470611/9b138552-19d3-4da3-bfb8-55398b5808a3)
**ISP:**
![image](https://github.com/GordonL0049/OpenAI/assets/119470611/64bef09a-1492-43e5-b856-4d45a05103d3)
![image](https://github.com/GordonL0049/OpenAI/assets/119470611/8762e48a-6ff9-44a0-b1ca-57d766be02ed)
![image](https://github.com/GordonL0049/OpenAI/assets/119470611/6e8271a1-27e2-4074-817e-b8b8959590ad)
UML:
![image](https://github.com/GordonL0049/OpenAI/assets/119470611/9ed5e6bf-f5c8-4662-aff6-561411f2b517)
**DIP:**
![image](https://github.com/GordonL0049/OpenAI/assets/119470611/14a9452d-fcda-4d84-934d-39e1defb07f1)
![image](https://github.com/GordonL0049/OpenAI/assets/119470611/11c49784-25b9-4e98-bf94-82884564c8d8)
![image](https://github.com/GordonL0049/OpenAI/assets/119470611/00356a65-0d2a-43a7-9ae1-8074a57ee246)
UML:
![image](https://github.com/GordonL0049/OpenAI/assets/119470611/a0c5045d-da6b-4658-a28e-a99517bdfc95)

**Comment by gordonlu310-old** [comment]
...and what do you mean? How is this related to the extension? Does this fix any bugs?
